wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: CNN
input_shape:
  desc: null
  value:
  - 160
  - 160
  - 3
epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 32
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.0
    framework: huggingface
    huggingface_version: 4.51.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1745122221.214921
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 41
      - 49
      - 55
      2:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 41
      - 49
      - 55
      - 63
      3:
      - 3
      - 8
      - 16
      - 23
      4: 3.9.13
      5: 0.15.0
      6: 4.51.3
      8:
      - 4
      - 5
      10:
      - 9
